"use strict";
// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.loadFormatters = exports.loadAllLocales = exports.loadLocale = void 0;
const formatters_1 = require("./formatters");
const i18n_util_1 = require("./i18n-util");
const af_1 = __importDefault(require("./af"));
const ar_1 = __importDefault(require("./ar"));
const ca_1 = __importDefault(require("./ca"));
const cs_1 = __importDefault(require("./cs"));
const de_1 = __importDefault(require("./de"));
const el_1 = __importDefault(require("./el"));
const en_1 = __importDefault(require("./en"));
const es_1 = __importDefault(require("./es"));
const fr_1 = __importDefault(require("./fr"));
const hr_1 = __importDefault(require("./hr"));
const hy_1 = __importDefault(require("./hy"));
const it_1 = __importDefault(require("./it"));
const ms_1 = __importDefault(require("./ms"));
const nl_1 = __importDefault(require("./nl"));
const pt_1 = __importDefault(require("./pt"));
const qu_1 = __importDefault(require("./qu"));
const sr_1 = __importDefault(require("./sr"));
const sw_1 = __importDefault(require("./sw"));
const th_1 = __importDefault(require("./th"));
const tr_1 = __importDefault(require("./tr"));
const vi_1 = __importDefault(require("./vi"));
const localeTranslations = {
    af: af_1.default,
    ar: ar_1.default,
    ca: ca_1.default,
    cs: cs_1.default,
    de: de_1.default,
    el: el_1.default,
    en: en_1.default,
    es: es_1.default,
    fr: fr_1.default,
    hr: hr_1.default,
    hy: hy_1.default,
    it: it_1.default,
    ms: ms_1.default,
    nl: nl_1.default,
    pt: pt_1.default,
    qu: qu_1.default,
    sr: sr_1.default,
    sw: sw_1.default,
    th: th_1.default,
    tr: tr_1.default,
    vi: vi_1.default,
};
const loadLocale = (locale) => {
    if (i18n_util_1.loadedLocales[locale])
        return;
    i18n_util_1.loadedLocales[locale] = localeTranslations[locale];
    (0, exports.loadFormatters)(locale);
};
exports.loadLocale = loadLocale;
const loadAllLocales = () => i18n_util_1.locales.forEach(exports.loadLocale);
exports.loadAllLocales = loadAllLocales;
const loadFormatters = (locale) => void (i18n_util_1.loadedFormatters[locale] = (0, formatters_1.initFormatters)(locale));
exports.loadFormatters = loadFormatters;
//# sourceMappingURL=i18n-util.sync.js.map