"use strict";
// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.detectLocale = exports.i18n = exports.i18nObject = exports.i18nString = exports.extendDictionary = exports.loadedFormatters = exports.loadedLocales = exports.isLocale = exports.locales = exports.baseLocale = void 0;
const typesafe_i18n_1 = require("typesafe-i18n");
const detectors_1 = require("typesafe-i18n/detectors");
const utils_1 = require("typesafe-i18n/utils");
exports.baseLocale = 'en';
exports.locales = [
    'af',
    'ar',
    'ca',
    'cs',
    'de',
    'el',
    'en',
    'es',
    'fr',
    'hr',
    'hy',
    'it',
    'ms',
    'nl',
    'pt',
    'qu',
    'sr',
    'sw',
    'th',
    'tr',
    'vi'
];
const isLocale = (locale) => exports.locales.includes(locale);
exports.isLocale = isLocale;
exports.loadedLocales = {};
exports.loadedFormatters = {};
exports.extendDictionary = (0, utils_1.initExtendDictionary)();
const i18nString = (locale) => (0, typesafe_i18n_1.i18nString)(locale, exports.loadedFormatters[locale]);
exports.i18nString = i18nString;
const i18nObject = (locale) => (0, typesafe_i18n_1.i18nObject)(locale, exports.loadedLocales[locale], exports.loadedFormatters[locale]);
exports.i18nObject = i18nObject;
const i18n = () => (0, typesafe_i18n_1.i18n)(exports.loadedLocales, exports.loadedFormatters);
exports.i18n = i18n;
const detectLocale = (...detectors) => (0, detectors_1.detectLocale)(exports.baseLocale, exports.locales, ...detectors);
exports.detectLocale = detectLocale;
//# sourceMappingURL=i18n-util.js.map