"use strict";
// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.loadFormatters = exports.loadAllLocalesAsync = exports.loadLocaleAsync = exports.importLocaleAsync = void 0;
const formatters_1 = require("./formatters");
const i18n_util_1 = require("./i18n-util");
const localeTranslationLoaders = {
    af: () => import('./af'),
    ar: () => import('./ar'),
    ca: () => import('./ca'),
    cs: () => import('./cs'),
    de: () => import('./de'),
    el: () => import('./el'),
    en: () => import('./en'),
    es: () => import('./es'),
    fr: () => import('./fr'),
    hr: () => import('./hr'),
    hy: () => import('./hy'),
    it: () => import('./it'),
    ms: () => import('./ms'),
    nl: () => import('./nl'),
    pt: () => import('./pt'),
    qu: () => import('./qu'),
    sr: () => import('./sr'),
    sw: () => import('./sw'),
    th: () => import('./th'),
    tr: () => import('./tr'),
    vi: () => import('./vi'),
};
const updateDictionary = (locale, dictionary) => i18n_util_1.loadedLocales[locale] = Object.assign(Object.assign({}, i18n_util_1.loadedLocales[locale]), dictionary);
const importLocaleAsync = async (locale) => (await localeTranslationLoaders[locale]()).default;
exports.importLocaleAsync = importLocaleAsync;
const loadLocaleAsync = async (locale) => {
    updateDictionary(locale, await (0, exports.importLocaleAsync)(locale));
    (0, exports.loadFormatters)(locale);
};
exports.loadLocaleAsync = loadLocaleAsync;
const loadAllLocalesAsync = () => Promise.all(i18n_util_1.locales.map(exports.loadLocaleAsync));
exports.loadAllLocalesAsync = loadAllLocalesAsync;
const loadFormatters = (locale) => void (i18n_util_1.loadedFormatters[locale] = (0, formatters_1.initFormatters)(locale));
exports.loadFormatters = loadFormatters;
//# sourceMappingURL=i18n-util.async.js.map