"use strict";
// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.useI18nContext = exports.I18nContext = void 0;
const react_1 = require("react");
const react_2 = require("typesafe-i18n/react");
const i18n_util_1 = require("./i18n-util");
const { component: TypesafeI18n, context: I18nContext } = (0, react_2.initI18nReact)(i18n_util_1.loadedLocales, i18n_util_1.loadedFormatters);
exports.I18nContext = I18nContext;
const useI18nContext = () => (0, react_1.useContext)(I18nContext);
exports.useI18nContext = useI18nContext;
exports.default = TypesafeI18n;
//# sourceMappingURL=i18n-react.js.map