version: 2.1

jobs:
  build_ios:
    macos:
      xcode: 16.2
    resource_class: macos.m1.medium.gen1 # 💡 balanced between performance & cost
    working_directory: ~/flash-mobile
    shell: /bin/bash --login -o pipefail
    environment:
      PUBLIC_VERSION: "0.1.0"
      BUILD_NUMBER: "100"

    steps:
      - checkout

      - run:
          name: Install Ruby and Bundler
          command: |
            brew install rbenv ruby-build
            rbenv install -s 3.2.2
            rbenv global 3.2.2
            gem install bundler -v 2.2.30

      - run:
          name: Install Dependencies
          command: |
            cd ios
            bundle install
            pod install

      # 👇 Fastlane build (same as local), but skip signing/uploading for testing
      - run:
          name: Build iOS (Debug mode, skip signing)
          command: |
            cd ios
            set -x
            bundle exec fastlane gym \
              --scheme "LNFlash" \
              --configuration "Debug" \
              --skip_codesigning true \
              --skip_package_ipa true \
              --clean \
              --verbose 2>&1 | tee ios_build_output.log

      - store_artifacts:
          path: ios/ios_build_output.log
          destination: ios_build_output.log

workflows:
  build_ios_workflow:
    jobs:
      - build_ios
