jobs:
  build_ios_test:
    macos:
      xcode: 16.2
    resource_class: macos.m1.medium.gen1 # ⚡ Cheaper & fast (~25 credits/min)
    working_directory: ~/flash-mobile
    environment:
      PUBLIC_VERSION: "0.1.0"
      BUILD_NUMBER: "100"
    shell: /bin/bash --login -o pipefail

    steps:
      - checkout

      - run:
          name: Install Ruby & Bundler
          command: |
            brew install rbenv ruby-build
            rbenv install -s 3.2.2
            rbenv global 3.2.2
            gem install bundler:2.2.30

      - run:
          name: Install Dependencies
          command: |
            cd ios
            bundle install
            pod install

      - run:
          name: Build with Fastlane (No Signing / No Upload)
          command: |
            cd ios
            bundle exec fastlane gym \
              --scheme "LNFlash" \
              --skip_codesigning true \
              --skip_package_ipa true \
              --configuration "Release" \
              --clean \
              --verbose 2>&1 | tee ios_build_output.log

      - persist_to_workspace:
          root: .
          paths:
            - ios/ios_build_output.log

      - store_artifacts:
          path: ios/ios_build_output.log
          destination: ios_build_output.log

      - add_ssh_keys:
          fingerprints:
            - "YOUR_SSH_KEY_FINGERPRINT" # optional if using SSH session

      - run:
          name: Enable SSH (for debugging)
          command: echo "You can now connect to this job using the CircleCI web UI → Rerun with SSH"
workflows:
  build_ios_test_workflow:
    jobs:
      - build_ios_test
