/**
 * key-owner — which account a local Nostr key belongs to.
 *
 * Every guard in the ensurer and in saveNewNostrKey reads this record; if it
 * is not written, read back, or cleared correctly, a key generated by account
 * A is silently registered on account B on a shared phone.
 */
import AsyncStorage from "@react-native-async-storage/async-storage"
import { nip19 } from "nostr-tools"
import {
  clearNostrKeyOwners,
  getNostrKeyOwner,
  nostrKeyOwnerKey,
  setNostrKeyOwner,
} from "@app/nostr/key-owner"

const NPUB_1 = nip19.npubEncode("a".repeat(64))
const NPUB_2 = nip19.npubEncode("b".repeat(64))

describe("nostr key owner record", () => {
  beforeEach(async () => {
    await AsyncStorage.clear()
  })

  it("has no owner for a key nobody recorded", async () => {
    expect(await getNostrKeyOwner(NPUB_1)).toBeNull()
  })

  it("reads back the account that was recorded for a key", async () => {
    await setNostrKeyOwner(NPUB_1, "account-a")
    expect(await getNostrKeyOwner(NPUB_1)).toBe("account-a")
  })

  it("keys the record on the npub, so a different key does not inherit it", async () => {
    // An imported nsec or the nsec handed back at phone login replaces the
    // keychain entry underneath; the new key must start with no owner.
    await setNostrKeyOwner(NPUB_1, "account-a")
    expect(await getNostrKeyOwner(NPUB_2)).toBeNull()
    expect(nostrKeyOwnerKey(NPUB_1)).not.toBe(nostrKeyOwnerKey(NPUB_2))
  })

  it("overwrites the owner when a key is taken over", async () => {
    await setNostrKeyOwner(NPUB_1, "account-a")
    await setNostrKeyOwner(NPUB_1, "account-b")
    expect(await getNostrKeyOwner(NPUB_1)).toBe("account-b")
  })

  it("clears every owner record and nothing else", async () => {
    await setNostrKeyOwner(NPUB_1, "account-a")
    await setNostrKeyOwner(NPUB_2, "account-b")
    await AsyncStorage.setItem("lastSeen_x", "1")

    await clearNostrKeyOwners()

    expect(await getNostrKeyOwner(NPUB_1)).toBeNull()
    expect(await getNostrKeyOwner(NPUB_2)).toBeNull()
    expect(await AsyncStorage.getItem("lastSeen_x")).toBe("1")
  })

  it("clearing with no records is a no-op", async () => {
    await expect(clearNostrKeyOwners()).resolves.toBeUndefined()
  })
})
